---
- name: CONSUL | Call hitotito.consul service tasks
  include_role:
    name: hitotito.consul
    tasks_from: service
    private: yes
  vars:
    consul_service_name: "{{ phabricator_consul_service_name }}"
    consul_service_check: "http"
    consul_service_ports: ["{{ phabricator_port }}"]
