---
- name: install phabricator
  import_tasks: install.yml
  tags:
    - install

- name: install consul service definition
  import_tasks: consul.yml
  when: phabricator_consul_service_enabled
  tags:
    - consul_definition
